### ISSUE TITLE
Stop including a deprecated header that has been removed in current QT versions

### ISSUE THREAD

**Issue by drewwalton19216801** [team-phoenix/Phoenix#330] opened 2017-02-22 02:43 UTC
https://bugs.archlinux.org/task/52956

Self-explanatory.

**Comment by athairus** [comment] 2017-02-22 03:41
Duplicate of #329.

We do not include `qtmultimediadefs.h` in our codebase: https://github.com/team-phoenix/Phoenix/blob/master/frontend/cpp/frontendcommon.h#L12

The assessment Mr. Rojas made is wrong. There's nothing we can do about this from downstream, the issue is upstream. There was a packaging error caused by that deprecated header being present. It was fixed in the commit linked to that page and will appear when 5.8.1 is released.

Workaround is to wait for 5.8.1 to be released, build 5.8.1 yourself or use 5.7.x. Either way, Phoenix won't build at all with 5.8.0 on any OS, I've tested this myself.

**Closed by athairus** 2017-02-22 03:41 UTC
