### ISSUE TITLE
can't delete game (osx)

### ISSUE THREAD

**Issue by lilcdj** [team-phoenix/Phoenix#321] opened 2016-11-06 06:56 UTC
i try using Pheonix on osx and it's so beautiful! but i can't delete game which i doesn't want to play and display no more. how can i delete game on library?

**Comment by athairus** [comment] 2016-11-08 04:57
Not done yet. It'll be available in a later release.

Closed, duplicate of #152.

**Closed by athairus** 2016-11-08 04:57 UTC
