### ISSUE TITLE
Fails to find /usr/lib/libretro

### ISSUE THREAD

**Issue by parkerlreed** [team-phoenix/Phoenix#253] opened 2016-05-03 20:04 UTC
Arch x86_64
phoenix-git r1129.0a822e3-2
libretro-genesis-plus-gx 998-1

I go into settings and tell it to open the core folder. Doesn't find it.

````
[parker@e73 Videos]$ Phoenix 
phoenix.library: Installed mode
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Debug: Initializing database schema ((null):0, (null))
Debug: QSqlDatabase(driver="QSQLITE", database="/home/parker/.local/share/Team Phoenix/Phoenix/userdata.sqlite", host=
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Debug: PhxTheme: Using system font "Sans Serif" (qrc:/PhxTheme.qml:63, onCompleted)
Debug: currenttext:  Keyboard (qrc:/PhxComboBox.qml:13, onCurrentTextChanged)
Debug: Opening database /home/parker/.local/share/Team Phoenix/Phoenix/userdata.sqlite ((null):0, (null))
Debug: Opening database /usr/share/phoenix/Metadata//libretro.sqlite ((null):0, (null))
Debug: Opening custom controller DB file: /home/parker/.local/share/Team Phoenix/Phoenix/gamecontrollerdb.txt ((null):0, (null))
Debug: Loaded custom controller DB successfully. ((null):0, (null))
Warning: qrc:/PlatformsView.qml:160: TypeError: Cannot read property of null (qrc:/PlatformsView.qml:160, (null))
Warning: qrc:/PlatformsView.qml:160: TypeError: Cannot read property of null (qrc:/PlatformsView.qml:160, (null))
Warning: qrc:/PlatformsView.qml:176:23: Unable to assign [undefined] to QString (qrc:/PlatformsView.qml:176, (null))
Debug: transitionFinished() (qrc:/main.qml:148, transitionFinished)
xdg-open: file 'file://usr/lib/libretro' does not exist
xdg-open: file 'file://usr/lib/libretro' does not exist
````

````
[parker@e73 Videos]$ ls -lah /usr/lib/libretro/
total 5.7M
drwxr-xr-x   2 root root 4.0K May  3 02:11 .
drwxr-xr-x 228 root root 144K May  3 15:58 ..
-rw-r--r--   1 root root 5.6M May  3 02:11 genesis_plus_gx_libretro.so
````

Also there's a giant memory dump when I exited Phoenix

**Comment by athairus** [comment] 2016-05-03 20:06
It seems to be appending nothing to the hard-coded libretro path. What core is set for the Genesis under settings, and is that entry marked as green or red?

**Comment by parkerlreed** [comment] 2016-05-03 20:17
This is all I get in the setting pane.

![1462306594](https://cloud.githubusercontent.com/assets/841440/14996957/785a06fc-114a-11e6-9442-0ce774ac0016.png)

**Comment by athairus** [comment] 2016-05-03 20:18
That's strange! Can you confirm that `libretro.sqlite` exists on your filesystem at `[phoenix path]/../share/phoenix/Metadata`?

**Comment by parkerlreed** [comment] 2016-05-03 20:24
It is owned by root with 755 (user can't write to it) if that causes an issue.

````
/usr/share/phoenix/
└── Metadata
    ├── libretro.sqlite
    └── openvgdb.sqlite
````

````
.local/share/Team Phoenix/
└── Phoenix
    ├── Cover Art Cache
    │   └── 24AB4C3A.jpg
    ├── Firmware
    ├── gamecontrollerdb.txt
    ├── Logs
    │   ├── Tue May 3 2016 - 3 56 37 PM.log
    │   ├── Tue May 3 2016 - 3 58 21 PM.log
    │   ├── Tue May 3 2016 - 3 58 51 PM.log
    │   ├── Tue May 3 2016 - 4 00 46 PM.log
    │   └── Tue May 3 2016 - 4 16 13 PM.log
    ├── Saves
    └── userdata.sqlite
````

**Comment by athairus** [comment] 2016-05-03 20:31
Is the file empty? How about `openvgdb.sqlite`? Can you post the full log from the run in your screenshot, or better yet, all those logs zipped together?

**Comment by parkerlreed** [comment] 2016-05-03 20:39
[files.zip](https://github.com/team-phoenix/Phoenix/files/247720/files.zip)

**Comment by athairus** [comment] 2016-05-03 20:43
Your logs are all warning that the SQL database isn't open. Do you have another Phoenix process running? What version of Qt do you have installed?

**Comment by athairus** [comment] 2016-05-03 20:46
And like you mentioned earlier, root is the owner of the file and the user can't write to it. That means we probably can't open either the metadata db or the libretro db.

**Comment by parkerlreed** [comment] 2016-05-03 21:10
Ran chmod -R 777 on /usr/share/phoenix/ (And tried chown'ing) but same result.

[1.txt](https://github.com/team-phoenix/Phoenix/files/247775/1.txt)
[2.txt](https://github.com/team-phoenix/Phoenix/files/247774/2.txt)

**Comment by athairus** [comment] 2016-05-03 21:11
Could you tell me what version of Qt you have installed?

**Comment by parkerlreed** [comment] 2016-05-03 21:12
qt5-base 5.6.0-4

**Comment by athairus** [comment] 2016-05-06 00:43
Try looking at `userdata.sqlite` with an SQLite viewer. If it looks okay, try deleting or renaming it.

**Comment by parkerlreed** [comment] 2016-05-06 02:43
Same. userdata.sqlite looked fine so I deleted it and let it recreate but same result

![1462502486](https://cloud.githubusercontent.com/assets/841440/15062862/ad980ee4-1312-11e6-9ba2-cf1b43e41411.png)

````
phoenix.library: Installed mode
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Debug: Initializing database schema ((null):0, (null))
Debug: QSqlDatabase(driver="QSQLITE", database="/home/parker/.local/share/Team Phoenix/Phoenix/userdata.sqlite", hos
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Warning: QSqlQuery::exec: database not open ((null):0, (null))
Debug: PhxTheme: Using system font "Sans Serif" (qrc:/PhxTheme.qml:63, onCompleted)
Debug: currenttext:  Keyboard (qrc:/PhxComboBox.qml:13, onCurrentTextChanged)
Debug: Opening database /home/parker/.local/share/Team Phoenix/Phoenix/userdata.sqlite ((null):0, (null))
Debug: Opening database /usr/share/phoenix/Metadata//libretro.sqlite ((null):0, (null))
Debug: Opening custom controller DB file: /home/parker/.local/share/Team Phoenix/Phoenix/gamecontrollerdb.txt ((null):0, (null))
Debug: Loaded custom controller DB successfully. ((null):0, (null))
Warning: qrc:/PlatformsView.qml:160: TypeError: Cannot read property of null (qrc:/PlatformsView.qml:160, (null))
Warning: qrc:/PlatformsView.qml:160: TypeError: Cannot read property of null (qrc:/PlatformsView.qml:160, (null))
Warning: qrc:/PlatformsView.qml:176:23: Unable to assign [undefined] to QString (qrc:/PlatformsView.qml:176, (null))
Debug: transitionFinished() (qrc:/main.qml:148, transitionFinished)
Debug:  ((null):0, (null))
Info: >>>>>>>> User requested app to close, shutting down (waiting up to 30 seconds)... ((null):0, (null))
Debug:  ((null):0, (null))
Debug: No core running, continuing ((null):0, (null))
Debug: No connections to disconnect, continuing ((null):0, (null))
Debug: No threads to delete, continuing ((null):0, (null))
Debug: No children in game thread to delete, continuing ((null):0, (null))
Debug: Fully unloaded ((null):0, (null))
Debug:  ((null):0, (null))
Info: >>>>>>>> Fully unloaded, quitting! ((null):0, (null))
Debug:  ((null):0, (null))
Debug:  ((null):0, (null))
Info: >>>>>>>> User requested app to close, shutting down GameHasher (waiting up to 30 seconds)... ((null):0, (null))
Debug:  ((null):0, (null))
Debug: No scan active, continuing ((null):0, (null))
Debug: Fully unloaded ((null):0, (null))
Debug:  ((null):0, (null))
Info: >>>>>>>> Fully unloaded! ((null):0, (null))
Debug:  ((null):0, (null))
Debug: "/home/parker/.config/Team Phoenix/Phoenix.conf" ((null):0, (null))
````

**Comment by athairus** [comment] 2016-05-06 02:58
@Limero, as the package maintainer could you help this guy out? I'm not sure what's going on with his system. Are you getting other reports like this?

The fact the database isn't opening leads me to believe that maybe your version of Qt wasn't built with proper SQLite support or something. It's hard to tell.

**Comment by Limero** [comment] 2016-05-06 15:27
I tried doing a clean install and no cores are available in the settings panel for me neither. It looks like the path it's trying to use for loading the libretro database is "/usr/share/phoenix/Metadata//libretro.sqlite" instead of '/usr/share/phoenix/Metadata/libretro.sqlite'. Notice the double slashes in the path. When doing a portable build, no double slashes are added but it still seems to give the same problem, but that is the only thing I've found.

My regular userdata.sqlite is loaded correctly because all the games that I previously imported are there, so there shouldn't be any problem with SQLite support.

**Comment by athairus** [comment] 2016-06-06 16:36
This bug was caused by a silly mistake on my part. Fixed.

**Closed by athairus** 2016-06-06 16:36 UTC

**Comment by parkerlreed** [comment] 2016-06-06 16:43
Cheers! I'll give it a shot in a few minutes.

**Comment by parkerlreed** [comment] 2016-06-06 17:00
Oh my! It works and holy crap. This is freaking nice. I like how it treats the game like a video with the pause controls and fullscreen/etc. Thanks for the update.

**Comment by athairus** [comment] 2016-06-06 17:01
Glad to hear. Just wait when we merge `feature-pipeline`. We've been working on that for the last month or so with all kinds of background improvements.
