### ISSUE TITLE
Game grouping

### ISSUE THREAD

**Issue by Druage** [team-phoenix/Phoenix#11] opened 2014-10-03 16:20 UTC
Say you have multiple versions of the same game, or hacked versions that you would like to not visually clog the grid.

This issue can be rectified by grouping games that share the same base name. Only one spot on the grid will house several versions, and they will all share the same artwork by default. 

When you click on the group, the most popular version will be used by default, but you will be able to change this behavior by having a group icon show on the artwork when the mouse hovers over. When you click on this group button, you will be presented with something like [this](http://wpuploads.appadvice.com/wp-content/uploads/2013/06/iOS-7-Folders-576x1024.png)

The same behavior will be on the table, except the groups will be text instead of images, such as [this](http://www.linux-ai.com/wp-content/uploads/images/elementary%20OS%20/elementary-luna-noise.png).

**Comment by athairus** [comment] 2016-04-07 20:15
My idea for implementing this:
- Store user preference for preferred regions in some way (ranked order ex. 1. World, 2. US, 3. JP, 4. EU, etc)
- Store a list of `releaseID`s, include a flag that indicates this was manually set
- When the user changes preferred region order, redo this list, leaving manually-flagged entries untouched
- To display, fetch the list and grab metadata for each `releaseID`

**Comment by athairus** [comment] 2016-05-13 20:14
Duplicate of #245

**Closed by athairus** 2016-05-13 20:14 UTC
Labels: enhancement, future addition, library
